name: workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
